# Generated by Django 4.0.10 on 2023-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_name_booking_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
